// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYxZaDzVC4nEXqdO287U5h00LuBryi7t0',
    appId: '1:955220275146:web:ef45f61c8d86c025aaa933',
    messagingSenderId: '955220275146',
    projectId: 'bongolava-guide-ia',
    authDomain: 'bongolava-guide-ia.firebaseapp.com',
    storageBucket: 'bongolava-guide-ia.firebasestorage.app',
    measurementId: 'G-DRV26PC9JJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBr01EXwNunz1GofWOppyGAcsmd3oORew',
    appId: '1:955220275146:android:44dca9ebece17a67aaa933',
    messagingSenderId: '955220275146',
    projectId: 'bongolava-guide-ia',
    storageBucket: 'bongolava-guide-ia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUgF37ahi04r67dv_fKjbN-SfH2xZ9hQ8',
    appId: '1:955220275146:ios:17c46a13f001ceb9aaa933',
    messagingSenderId: '955220275146',
    projectId: 'bongolava-guide-ia',
    storageBucket: 'bongolava-guide-ia.firebasestorage.app',
    iosBundleId: 'com.example.bongolavaAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUgF37ahi04r67dv_fKjbN-SfH2xZ9hQ8',
    appId: '1:955220275146:ios:17c46a13f001ceb9aaa933',
    messagingSenderId: '955220275146',
    projectId: 'bongolava-guide-ia',
    storageBucket: 'bongolava-guide-ia.firebasestorage.app',
    iosBundleId: 'com.example.bongolavaAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYxZaDzVC4nEXqdO287U5h00LuBryi7t0',
    appId: '1:955220275146:web:195f82308704839eaaa933',
    messagingSenderId: '955220275146',
    projectId: 'bongolava-guide-ia',
    authDomain: 'bongolava-guide-ia.firebaseapp.com',
    storageBucket: 'bongolava-guide-ia.firebasestorage.app',
    measurementId: 'G-KYNF5EP4K0',
  );
}
